sudo: required

env:
  global:
    secure: IZM73JJwd/vZ7W/0rYcIs9p4xClp1MlHZbsdOLJUSUXHTuoZtoXxqZBaoWI7emechR8grR/0wPUMBayuFvgFEPwmzerbJVjZivWqGipTBzr2xz/UdIet4wgFmpk50GHZ++31mdHL2P6uee2s8EBlRldBW47A7nTK67FJJvgQLzvMYqSroINegAeDO0q+FlQm17vnEmi/+mzro5dh6DPRJeELbkK9BEyZmmqsW54N/3y2cR0NodCBmJqkV/yXNUZ70uyHESR8RFFSaCBRxpcnkGp1/MdZ5qSMfzDUYd15qZDJpCa2kcGoJ6YwwCzCbsqBvVFuhiM5mH/itq7fPRXbRkV7g0WtrAt6lhdX/WSaEOd5MESepjPCIloeetlKbXmAqumiNglCHAjnWPtIgoXc+87ssiqoQ1thrZS2HCAdRrEfnrNlxAyTIMtoXseIvaOpGOsPpyS8u0aRFjOTK2iKvXOldnHUG0D2l7YxKlQDmdm7Y2v8o0S356OJDz18TXddqkZLjyyCiWoJ+W8dvsN1vd0gONaJfyX6p65rzwK9MJWkGXXjzCPYqNS99BqKxhTwppXUTK0jVKAh+jf/xB+bFe28KTBLHMHpRQ/8DryVLOg0QhwwTCQtlDlooT1gZqwHbEB7OrzEZ29aHRxB7RibhCPzMuYNng1KVQz64SX3eHg=
language: go

go:
  - 1.7

services:
  - docker

install:
  - go get github.com/aktau/github-release
  - go install .

script: walk -v test
